const galileeInsights = {
  cana_sign: {
    title: {
      it: "Il Segno della Nuova Creazione",
      en: "The Sign of the New Creation"
    },
    content: {
      it: "Il miracolo di Cana non è solo un atto di compassione sociale, ma il primo 'segno' (semeion) che rivela la gloria di Cristo. Le sei giare di pietra, vuote e usate per i riti di purificazione giudaica, rappresentano il sistema della Legge giunto al suo esaurimento. L'acqua trasformata in vino eccellente e abbondante simboleggia la Nuova Alleanza: la Legge fredda della religione viene sostituita dalla gioia traboccante, vitale e immeritata della Grazia divina.",
      en: "The miracle at Cana is not merely an act of social compassion, but the first 'sign' (semeion) revealing Christ's glory. The six stone jars, empty and used for Jewish purification rites, represent the system of the Law having reached its exhaustion. The water transformed into excellent and abundant wine symbolizes the New Covenant: the cold Law of religion is replaced by the overflowing, vital, and unmerited joy of divine Grace."
    },
    refs: {
      it: "Giovanni 1:17: 'Perché la legge è stata data per mezzo di Mosè; la grazia e la verità sono venute per mezzo di Gesù Cristo.'\nIsaia 25:6: 'Il Signore degli eserciti preparerà per tutti i popoli... un convito di vini vecchi e chiarificati.'",
      en: "John 1:17: 'For the law was given through Moses; grace and truth came through Jesus Christ.'\nIsaiah 25:6: 'The LORD Almighty will prepare a feast of rich food for all peoples, a banquet of aged wine.'"
    }
  },
  immediate_response: {
    title: {
      it: "La Risposta Immediata",
      en: "The Immediate Response"
    },
    content: {
      it: "La chiamata dei primi discepoli evidenzia la natura irrevocabile dell'elezione divina. Gesù non invita a una blanda consultazione, ma emette un comando: 'Seguitemi'. La loro risposta immediata (abbandonando reti e famigliari) illustra la potenza efficace della chiamata di grazia. Costituisce il modello del discepolato radicale: non si tratta di aggiungere Gesù a una vita già piena, ma di abbandonare le certezze per arrendersi alla Sua Signoria totale.",
      en: "The calling of the first disciples highlights the irrevocable nature of divine election. Jesus does not invite them to a mild consultation, but issues a command: 'Follow me'. Their immediate response (leaving behind nets and family) illustrates the internal, effectual power of the call of grace. It constitutes the model of radical discipleship: it is not about adding Jesus to an already full life, but abandoning earthly certainties to surrender to His total Lordship."
    },
    refs: {
      it: "Filippesi 3:7-8: 'Ma ciò che per me era un guadagno, l'ho considerato come un danno a causa di Cristo...'\nLuca 9:62: 'Nessuno che ha messo la mano all'aratro e poi si volge indietro, è adatto per il regno di Dio.'",
      en: "Philippians 3:7-8: 'But whatever were gains to me I now consider loss for the sake of Christ...'\nLuke 9:62: 'No one who puts a hand to the plow and looks back is fit for service in the kingdom of God.'"
    }
  },
  kingdom_character: {
    title: {
      it: "Il Carattere del Regno",
      en: "The Character of the Kingdom"
    },
    content: {
      it: "Nelle Beatitudini, Gesù ribalta completamente i valori del mondo decaduto e le aspettative del legalismo religioso farisaico. Il Regno non viene inaugurato dalla forza militare o dall'osservanza esteriore, ma è riversato sui 'poveri in spirito'—coloro che riconoscono la loro totale bancarotta morale davanti a Dio. Questa giustizia non è una lista di regole da conquistare, ma la condizione interiore di un cuore profondamente trasformato e rigenerato dallo Spirito.",
      en: "In the Beatitudes, Jesus completely overturns the values of the fallen world and the expectations of Pharisaical religious legalism. The Kingdom is not inaugurated by military force or outward observance, but is poured out upon the 'poor in spirit'—those who recognize their total moral bankruptcy before God. This righteousness is not a list of rules to be conquered, but the inward condition of a heart profoundly transformed and regenerated by the Spirit."
    },
    refs: {
      it: "Romani 14:17: 'Perché il regno di Dio non consiste in vivanda né in bevanda, ma è giustizia, pace e gioia nello Spirito Santo.'\nIsaia 66:2: 'A chi dunque guarderò io? All'umile e al contrito di spirito...'",
      en: "Romans 14:17: 'For the kingdom of God is not a matter of eating and drinking, but of righteousness, peace and joy in the Holy Spirit.'\nIsaiah 66:2: 'These are the ones I look on with favor: those who are humble and contrite in spirit...'"
    }
  },
  authority_forgive: {
    title: {
      it: "Autorità di Perdonare",
      en: "Authority to Forgive"
    },
    content: {
      it: "Guarendo il paralitico, Gesù affronta il bisogno più urgente e letale dell'umanità: non la sofferenza fisica, ma il peccato. Perdonando i peccati prima di curare il corpo, Gesù dichiara pubblicamente la Sua divinità, attribuendosi una prerogativa che appartiene esclusivamente a Dio. La guarigione fisica che ne consegue è il miracolo esteriore che convalida la realtà del miracolo più grande compiuto nell'invisibile: il perdono dei peccati.",
      en: "By healing the paralytic, Jesus addresses humanity's most urgent and lethal need: not physical suffering, but sin. By forgiving sins before curing the body, Jesus publicly declares His divinity, claiming a prerogative belonging exclusively to God. The subsequent physical healing is the outward miracle that validates the reality of the greater miracle performed in the invisible: the absolution and forgiveness of sins."
    },
    refs: {
      it: "Michea 7:18-19: 'Qual Dio è come te, che perdona l'iniquità... Egli calpesterà le nostre colpe, tu getterai in fondo al mare tutti i nostri peccati.'\nColossesi 1:13-14: 'In lui abbiamo la redenzione, il perdono dei peccati.'",
      en: "Micah 7:18-19: 'Who is a God like you, who pardons sin... You will tread our sins underfoot and hurl all our iniquities into the depths of the sea.'\nColossians 1:13-14: 'In whom we have redemption, the forgiveness of sins.'"
    }
  },
  faith_vs_fear: {
    title: {
      it: "Fede contro Paura",
      en: "Faith vs. Fear"
    },
    content: {
      it: "La tempesta sedata è una maestosa teofania della Creazione. Proprio come l'Eterno impose limiti al mare in Genesi, così Gesù sottomette la tempesta caotica con una sola parola. La paura dei discepoli è rimpiazzata da un 'grande timore' referenziale verso Cristo, realizzando di avere Dio stesso sulla barca. La fede salvifica non è credere che non ci saranno tempeste, ma riposare nell'assoluta sovranità di Colui a cui persino i venti e l'acqua ubbidiscono.",
      en: "The calming of the storm is a majestic theophany of Creation. Just as the Eternal imposed limits on the sea in Genesis, so Jesus subdues the chaotic storm with a single word. The disciples' situational fear is replaced by a 'great reverence' toward Christ, realizing they have God Himself in the boat. Saving faith is not believing there will be no storms, but resting in the absolute sovereignty of Him whom even the winds and the water obey."
    },
    refs: {
      it: "Salmo 89:9: 'Tu domini l'orgoglio del mare; quando le sue onde s'innalzano, tu le plachi.'\nProverbi 30:4: 'Chi ha raccolto il vento nel suo pugno? Chi ha racchiuso le acque in una veste? Qual è il suo nome?'",
      en: "Psalm 89:9: 'You rule over the surging sea; when its waves mount up, you still them.'\nProverbs 30:4: 'Who has caught the wind in his lap? Who has wrapped up the waters in a cloak? What is his name?'"
    }
  },
  kingdom_first: {
    title: {
      it: "La Priorità del Regno",
      en: "The Priority of the Kingdom"
    },
    content: {
      it: "Gesù non proibisce semplicemente l'ansia, ma offre una soluzione: la sostituzione degli affetti. L'ansia è presentata come una forma di idolatria che nasce dalla sfiducia nella provvidenza del Padre. Cercare 'prima' il Regno significa riconoscere che la sovranità di Dio non è solo un concetto teologico, ma la realtà suprema che deve guidare ogni priorità quotidiana, confidando che il Padre provvederà a tutto il resto.",
      en: "Jesus does not simply forbid anxiety but offers a solution: the replacement of affections. Anxiety is presented as a form of idolatry arising from distrust in the Father's providence. Seeking 'first' the Kingdom means recognizing that God's sovereignty is not just a theological concept, but the supreme reality that must guide every daily priority, trusting that the Father will provide for everything else."
    },
    refs: {
      it: "Luca 12:30: 'Il Padre vostro sa che avete bisogno di queste cose.'\nSalmo 37:4: 'Prendi il tuo diletto nel Signore ed egli ti darà quel che il tuo cuore desidera.'",
      en: "Luke 12:30: 'Your Father knows that you need them.'\nPsalm 37:4: 'Delight yourself in the LORD, and he will give you the desires of your heart.'"
    }
  },
  narrow_gate_choice: {
    title: {
      it: "La Porta Stretta",
      en: "The Narrow Gate"
    },
    content: {
      it: "L'esortazione di Gesù mette in guardia contro una spiritualità superficiale e accomodante. La 'porta stretta' rappresenta la via dell'umiltà, del ravvedimento e della sottomissione alla Sua Signoria, contrapposta alla 'via spaziosa' dell'auto-giustificazione e della compiacenza mondana. La salvezza non è un cammino di massa, ma una scelta radicale dell'individuo che risponde alla grazia di Dio camminando in controtendenza rispetto al mondo.",
      en: "Jesus' exhortation warns against a superficial and accommodating spirituality. The 'narrow gate' represents the path of humility, repentance, and submission to His Lordship, contrasted with the 'broad road' of self-righteousness and worldly complacency. Salvation is not a mass path, but an individual's radical choice in response to God's grace, walking in a direction opposite to the world."
    },
    refs: {
      it: "Giovanni 14:6: 'Gesù gli disse: «Io sono la via, la verità e la vita; nessuno viene al Padre se non per mezzo di me.»'\nMatteo 16:24: 'Se uno vuol venire dietro a me, rinunzi a se stesso, prenda la sua croce e mi segua.'",
      en: "John 14:6: 'Jesus answered: I am the way and the truth and the life. No one comes to the Father except through me.'\nMatthew 16:24: 'Whoever wants to be my disciple must deny themselves and take up their cross and follow me.'"
    }
  },
  foundation_rock: {
    title: {
      it: "Fondamento sulla Roccia",
      en: "Foundation on the Rock"
    },
    content: {
      it: "La parabola finale del Sermone sul Monte sottolinea che la vera saggezza non consiste nell'accumulare conoscenza teologica, ma nell'ubbidienza pratica. Entrambi i costruttori ascoltano le parole di Gesù; la distinzione cruciale risiede nell'applicazione. Il fondamento sulla roccia è l'unione vitale con Cristo attraverso la fede ubbidiente, l'unica base in grado di resistere alle tempeste del giudizio e delle prove della vita.",
      en: "The final parable of the Sermon on the Mount emphasizes that true wisdom consists not in accumulating theological knowledge, but in practical obedience. Both builders hear Jesus' words; the crucial distinction lies in the application. The foundation on the rock is vital union with Christ through obedient faith, the only base capable of withstanding the storms of judgment and the trials of life."
    },
    refs: {
      it: "Giacomo 1:22: 'Ma mettete in pratica la parola e non ascoltatela soltanto, illudendo voi stessi.'\n1 Corinzi 3:11: 'Nessuno può porre altro fondamento oltre a quello già posto, cioè Gesù Cristo.'",
      en: "James 1:22: 'Do not merely listen to the word, and so deceive yourselves. Do what it says.'\n1 Corinthians 3:11: 'For no one can lay any foundation other than the one already laid, which is Jesus Christ.'"
    }
  }
};

export default galileeInsights;
