const galileeInsights = {
  cana_sign: {
    title: {
      it: "Il Segno della Nuova Creazione",
      en: "The Sign of the New Creation"
    },
    content: {
      it: "Il miracolo di Cana non è solo un atto di compassione sociale, ma il primo 'segno' (semeion) che rivela la gloria di Cristo. Le sei giare di pietra, vuote e usate per i riti di purificazione giudaica, rappresentano il sistema della Legge giunto al suo esaurimento. L'acqua trasformata in vino eccellente e abbondante simboleggia la Nuova Alleanza: la Legge fredda della religione viene sostituita dalla gioia traboccante, vitale e immeritata della Grazia divina.",
      en: "The miracle at Cana is not merely an act of social compassion, but the first 'sign' (semeion) revealing Christ's glory. The six stone jars, empty and used for Jewish purification rites, represent the system of the Law having reached its exhaustion. The water transformed into excellent and abundant wine symbolizes the New Covenant: the cold Law of religion is replaced by the overflowing, vital, and unmerited joy of divine Grace."
    },
    refs: {
      it: "Giovanni 1:17: 'Perché la legge è stata data per mezzo di Mosè; la grazia e la verità sono venute per mezzo di Gesù Cristo.'\nIsaia 25:6: 'Il Signore degli eserciti preparerà per tutti i popoli... un convito di vini vecchi e chiarificati.'",
      en: "John 1:17: 'For the law was given through Moses; grace and truth came through Jesus Christ.'\nIsaiah 25:6: 'The LORD Almighty will prepare a feast of rich food for all peoples, a banquet of aged wine.'"
    }
  },
  immediate_response: {
    title: {
      it: "La Risposta Immediata",
      en: "The Immediate Response"
    },
    content: {
      it: "La chiamata dei primi discepoli evidenzia la natura irrevocabile dell'elezione divina. Gesù non invita a una blanda consultazione, ma emette un comando: 'Seguitemi'. La loro risposta immediata (abbandonando reti e famigliari) illustra la potenza efficace della chiamata di grazia. Costituisce il modello del discepolato radicale: non si tratta di aggiungere Gesù a una vita già piena, ma di abbandonare le certezze per arrendersi alla Sua Signoria totale.",
      en: "The calling of the first disciples highlights the irrevocable nature of divine election. Jesus does not invite them to a mild consultation, but issues a command: 'Follow me'. Their immediate response (leaving behind nets and family) illustrates the internal, effectual power of the call of grace. It constitutes the model of radical discipleship: it is not about adding Jesus to an already full life, but abandoning earthly certainties to surrender to His total Lordship."
    },
    refs: {
      it: "Filippesi 3:7-8: 'Ma ciò che per me era un guadagno, l'ho considerato come un danno a causa di Cristo...'\nLuca 9:62: 'Nessuno che ha messo la mano all'aratro e poi si volge indietro, è adatto per il regno di Dio.'",
      en: "Philippians 3:7-8: 'But whatever were gains to me I now consider loss for the sake of Christ...'\nLuke 9:62: 'No one who puts a hand to the plow and looks back is fit for service in the kingdom of God.'"
    }
  },
  kingdom_character: {
    title: {
      it: "Il Carattere del Regno",
      en: "The Character of the Kingdom"
    },
    content: {
      it: "Nelle Beatitudini, Gesù ribalta completamente i valori del mondo decaduto e le aspettative del legalismo religioso farisaico. Il Regno non viene inaugurato dalla forza militare o dall'osservanza esteriore, ma è riversato sui 'poveri in spirito'—coloro che riconoscono la loro totale bancarotta morale davanti a Dio. Questa giustizia non è una lista di regole da conquistare, ma la condizione interiore di un cuore profondamente trasformato e rigenerato dallo Spirito.",
      en: "In the Beatitudes, Jesus completely overturns the values of the fallen world and the expectations of Pharisaical religious legalism. The Kingdom is not inaugurated by military force or outward observance, but is poured out upon the 'poor in spirit'—those who recognize their total moral bankruptcy before God. This righteousness is not a list of rules to be conquered, but the inward condition of a heart profoundly transformed and regenerated by the Spirit."
    },
    refs: {
      it: "Romani 14:17: 'Perché il regno di Dio non consiste in vivanda né in bevanda, ma è giustizia, pace e gioia nello Spirito Santo.'\nIsaia 66:2: 'A chi dunque guarderò io? All'umile e al contrito di spirito...'",
      en: "Romans 14:17: 'For the kingdom of God is not a matter of eating and drinking, but of righteousness, peace and joy in the Holy Spirit.'\nIsaiah 66:2: 'These are the ones I look on with favor: those who are humble and contrite in spirit...'"
    }
  },
  authority_forgive: {
    title: {
      it: "Autorità di Perdonare",
      en: "Authority to Forgive"
    },
    content: {
      it: "Guarendo il paralitico, Gesù affronta il bisogno più urgente e letale dell'umanità: non la sofferenza fisica, ma il peccato. Perdonando i peccati prima di curare il corpo, Gesù dichiara pubblicamente la Sua divinità, attribuendosi una prerogativa che appartiene esclusivamente a Dio. La guarigione fisica che ne consegue è il miracolo esteriore che convalida la realtà del miracolo più grande compiuto nell'invisibile: il perdono dei peccati.",
      en: "By healing the paralytic, Jesus addresses humanity's most urgent and lethal need: not physical suffering, but sin. By forgiving sins before curing the body, Jesus publicly declares His divinity, claiming a prerogative belonging exclusively to God. The subsequent physical healing is the outward miracle that validates the reality of the greater miracle performed in the invisible: the absolution and forgiveness of sins."
    },
    refs: {
      it: "Michea 7:18-19: 'Qual Dio è come te, che perdona l'iniquità... Egli calpesterà le nostre colpe, tu getterai in fondo al mare tutti i nostri peccati.'\nColossesi 1:13-14: 'In lui abbiamo la redenzione, il perdono dei peccati.'",
      en: "Micah 7:18-19: 'Who is a God like you, who pardons sin... You will tread our sins underfoot and hurl all our iniquities into the depths of the sea.'\nColossians 1:13-14: 'In whom we have redemption, the forgiveness of sins.'"
    }
  },
  faith_vs_fear: {
    title: {
      it: "Fede contro Paura",
      en: "Faith vs. Fear"
    },
    content: {
      it: "La tempesta sedata è una maestosa teofania della Creazione. Proprio come l'Eterno impose limiti al mare in Genesi, così Gesù sottomette la tempesta caotica con una sola parola. La paura dei discepoli è rimpiazzata da un 'grande timore' referenziale verso Cristo, realizzando di avere Dio stesso sulla barca. La fede salvifica non è credere che non ci saranno tempeste, ma riposare nell'assoluta sovranità di Colui a cui persino i venti e l'acqua ubbidiscono.",
      en: "The calming of the storm is a majestic theophany of Creation. Just as the Eternal imposed limits on the sea in Genesis, so Jesus subdues the chaotic storm with a single word. The disciples' situational fear is replaced by a 'great reverence' toward Christ, realizing they have God Himself in the boat. Saving faith is not believing there will be no storms, but resting in the absolute sovereignty of Him whom even the winds and the water obey."
    },
    refs: {
      it: "Salmo 89:9: 'Tu domini l'orgoglio del mare; quando le sue onde s'innalzano, tu le plachi.'\nProverbi 30:4: 'Chi ha raccolto il vento nel suo pugno? Chi ha racchiuso le acque in una veste? Qual è il suo nome?'",
      en: "Psalm 89:9: 'You rule over the surging sea; when its waves mount up, you still them.'\nProverbs 30:4: 'Who has caught the wind in his lap? Who has wrapped up the waters in a cloak? What is his name?'"
    }
  },
  kingdom_first: {
    title: {
      it: "La Priorità del Regno",
      en: "The Priority of the Kingdom"
    },
    content: {
      it: "Gesù non proibisce semplicemente l'ansia, ma offre una soluzione: la sostituzione degli affetti. L'ansia è presentata come una forma di idolatria che nasce dalla sfiducia nella provvidenza del Padre. Cercare 'prima' il Regno significa riconoscere che la sovranità di Dio non è solo un concept teologico, ma la realtà suprema che deve guidare ogni priorità quotidiana, confidando che il Padre provvederà a tutto il resto.",
      en: "Jesus does not simply forbid anxiety but offers a solution: the replacement of affections. Anxiety is presented as a form of idolatry arising from distrust in the Father's providence. Seeking 'first' the Kingdom means recognizing that God's sovereignty is not just a theological concept, but the supreme reality that must guide every daily priority, trusting that the Father will provide for everything else."
    },
    refs: {
      it: "Luca 12:30: 'Il Padre vostro sa che avete bisogno di queste cose.'\nSalmo 37:4: 'Prendi il tuo diletto nel Signore ed egli ti darà quel che il tuo cuore desidera.'",
      en: "Luke 12:30: 'Your Father knows that you need them.'\nPsalm 37:4: 'Delight yourself in the LORD, and he will give you the desires of your heart.'"
    }
  },
  narrow_gate_choice: {
    title: {
      it: "La Porta Stretta",
      en: "The Narrow Gate"
    },
    content: {
      it: "L'esortazione di Gesù mette in guardia contro una spiritualità superficiale e accomodante. La 'porta stretta' rappresenta la via dell'umiltà, del ravvedimento e della sottomissione alla Sua Signoria, contrapposta alla 'via spaziosa' dell'auto-giustificazione e della compiacenza mondana. La salvezza non è un cammino di massa, ma una scelta radicale dell'individuo che risponde alla grazia di Dio camminando in controtendenza rispetto al mondo.",
      en: "Jesus' exhortation warns against a superficial and accommodating spirituality. The 'narrow gate' represents the path of humility, repentance, and submission to His Lordship, contrasted with the 'broad road' of self-righteousness and worldly complacency. Salvation is not a mass path, but an individual's radical choice in response to God's grace, walking in a direction opposite to the world."
    },
    refs: {
      it: "Giovanni 14:6: 'Gesù gli disse: «Io sono la via, la verità e la vita; nessuno viene al Padre se non per mezzo di me.»'\nMatteo 16:24: 'Se uno vuol venire dietro a me, rinunzi a se stesso, prenda la sua croce e mi segua.'",
      en: "John 14:6: 'Jesus answered: I am the way and the truth and the life. No one comes to the Father except through me.'\nMatthew 16:24: 'Whoever wants to be my disciple must deny themselves and take up their cross and follow me.'"
    }
  },
  foundation_rock: {
    title: {
      it: "Fondamento sulla Roccia",
      en: "Foundation on the Rock"
    },
    content: {
      it: "La parabola finale del Sermone sul Monte sottolinea che la vera saggezza non consiste nell'accumulare conoscenza teologica, ma nell'ubbidienza pratica. Entrambi i costruttori ascoltano le parole di Gesù; la distinzione cruciale risiede nell'applicazione. Il fondamento sulla roccia è l'unione vitale con Cristo attraverso la fede ubbidiente, l'unica base in grado di resistere alle tempeste del giudizio e delle prove della vita.",
      en: "The final parable of the Sermon on the Mount emphasizes that true wisdom consists not in accumulating theological knowledge, but in practical obedience. Both builders hear Jesus' words; the crucial distinction lies in the application. The foundation on the rock is vital union with Christ through obedient faith, the only base capable of withstanding the storms of judgment and the trials of life."
    },
    refs: {
      it: "Giacomo 1:22: 'Ma mettete in pratica la parola e non ascoltatela soltanto, illudendo voi stessi.'\n1 Corinzi 3:11: 'Nessuno può porre altro fondamento oltre a quello già posto, cioè Gesù Cristo.'",
      en: "James 1:22: 'Do not merely listen to the word, and so deceive yourselves. Do what it says.'\n1 Corinthians 3:11: 'For no one can lay any foundation other than the one already laid, which is Jesus Christ.'"
    }
  },
  new_birth: {
    title: { it: "La Nuova Nascita del Cuore", en: "The New Birth of the Heart" },
    content: {
      it: "Nel Sermone sul Monte, Gesù non si limita a riformare il comportamento esteriore, ma esige una giustizia che superi quella dei religiosi del tempo. Le Beatitudini e la legge dell'amore presuppongono un cuore rigenerato dallo Spirito Santo, capace di desiderare ciò che Dio desidera. Questa 'nuova nascita' è il motore interiore che trasforma l'ubbidienza da dovere legale a risposta gioiosa di un figlio verso il Padre.",
      en: "In the Sermon on the Mount, Jesus does not merely reform outward behavior; he demands a righteousness that exceeds that of the religious elite of his day. The Beatitudes and the law of love presuppose a heart regenerated by the Holy Spirit, capable of desiring what God desires. This 'new birth' is the inward engine that transforms obedience from a legal duty into the joyful response of a child to their Father."
    }
  },
  final_judgment: {
    title: { it: "Il Giudizio Finale", en: "The Final Judgment" },
    content: {
      it: "La parabola della zizzania rivela che la separazione tra il bene e il male non è immediata, ma avverrà alla fine dei tempi. Questo sottolinea la pazienza di Dio e la certezza di un giudizio giusto e definitivo, dove la vera natura dei cuori sarà rivelata davanti al Re.",
      en: "The parable of the weeds reveals that the separation between good and evil is not immediate but will occur at the end of time. This emphasizes God's patience and the certainty of a just and final judgment, where the true nature of hearts will be revealed before the King."
    }
  },
  sower_soils: {
    title: { it: "La Risposta del Cuore", en: "The Response of the Heart" },
    content: {
      it: "La parabola del seminatore non riguarda l'efficacia del seme (la Parola di Dio, che è perfetta), ma la condizione del terreno (il cuore umano). Gesù identifica quattro tipi di risposta: la durezza che impedisce la comprensione, la superficialità che cede alla prova, la mondanità che soffoca la crescita e, infine, la rigenerazione che porta frutto abbondante.",
      en: "The parable of the sower is not about the effectiveness of the seed (the Word of God, which is perfect), but the condition of the soil (the human heart). Jesus identifies four types of response: hardness that prevents understanding, shallowness that fails under trial, worldliness that chokes growth, and finally, regeneration that produces abundant fruit."
    }
  },
  mustard_leaven_growth: {
    title: { it: "La Crescita Invisibile", en: "The Invisible Growth" },
    content: {
      it: "Le parabole del granello di senape e del lievito illustrano la natura paradossale del Regno di Dio. Iniziando in modo piccolo e apparentemente insignificante, possiede una potenza vitale intrinseca che trasforma silenziosamente l'intera realtà. Il Regno non si impone con forza esterna, ma pervade la società e i cuori attraverso l'influenza inarrestabile della grazia.",
      en: "The parables of the mustard seed and the leaven illustrate the paradoxical nature of God's Kingdom. Starting small and seemingly insignificant, it possesses an internal vital power that silently transforms the whole of reality. The Kingdom does not impose itself with external force, but pervades society and hearts through the unstoppable influence of grace."
    }
  },
  treasure_pearl_value: {
    title: { it: "L'Incomparabile Valore", en: "The Incomparable Value" },
    content: {
      it: "Le parabole del tesoro e della perla insegnano che il Regno di Dio è un bene di valore infinito che supera ogni possedimento terreno. La gioia della scoperta porta a un abbandono totale e volontario di tutto il resto. Non è un sacrificio pesante, ma un investimento saggio: si cede ciò che non si può tenere per guadagnare ciò che non si può perdere.",
      en: "The parables of the treasure and the pearl teach that the Kingdom of God is a possession of infinite value surpassing all earthly belongings. The joy of discovery leads to a total and voluntary surrender of everything else. It is not a heavy sacrifice but a wise investment: giving up what you cannot keep to gain what you cannot lose."
    }
  },
  leper_stigma: {
    title: { it: "Lo Stigma della Lebbra", en: "The Stigma of Leprosy" },
    content: {
      it: "Nell'antichità, il lebbroso non era solo un malato, ma un emarginato rituale e sociale. Toccandolo, Gesù non solo lo guarisce fisicamente, ma abbatte le barriere dello stigma, restaurando la sua dignità e il suo posto nella comunità.",
      en: "In ancient times, a leper was not just a sick person but a ritual and social outcast. By touching him, Jesus not only heals him physically but breaks down the barriers of stigma, restoring his dignity and place in the community."
    }
  },
  centurion_faith: {
    title: { it: "La Fede del Centurione", en: "The Centurion's Faith" },
    content: {
      it: "La fede del centurione meraviglia Gesù perché riconosce l'autorità assoluta della Sua parola, senza necessità di una presenza fisica o di un segno visibile. Rappresenta l'apertura del Regno anche ai gentili (non ebrei).",
      en: "The centurion's faith amazes Jesus because it recognizes the absolute authority of His word, without needing physical presence or a visible sign. It represents the opening of the Kingdom even to the Gentiles (non-Jews)."
    }
  }
};

export default galileeInsights;
